RED - Introduces GameOfLife class
If you can't get the test to pass quickly, focus on changing the
*message* the test provides. This allows you to see if you're going in
the right direction.

By defining a class for GameOfLife, I expect that the message will
change from a "NameError" to something (hopefully) more useful in
guiding my implementation.

Expected Result of `bundle exec ruby test/all.rb`
=================================================

> # Running:
>
> E
>
> Finished in 0.001128s, 886.5248 runs/s, 0.0000 assertions/s.
>
>   1) Error:
> TestGameOfLife#test_a_con_at_5_5_with_no_neighbors_dies_after_one_day:
> ArgumentError: wrong number of arguments (1 for 0)
>     test/all.rb:11:in `initialize'
>     test/all.rb:11:in `new'
>     test/all.rb:11:in `test_a_con_at_5_5_with_no_neighbors_dies_after_one_day'
>
> 1 runs, 0 assertions, 0 failures, 1 errors, 0 skips

Oh hey! Look at that! We are now getting an ArgumentError! These two
lines tell me what to do:$

> ArgumentError: wrong number of arguments (1 for 0)
>     test/all.rb:11:in `initialize'

This tells me that `test/all.rb` on line 11 is trying to call a method
named initialize with an argument, but the method's definition doesn't
take an argument.

When we *look* at line 11, we see the following:

> game = GameOfLife.new(population)

What! Where's 'initialize'! It's no where in there! Let's look one line
further in the error message:

> test/all.rb:11:in `new'

Ah-ha! Initialize and new seem to have some kind of relationship. Let's
look into what new does in ruby¹, it turns out new:

* Allocates an instance of the GameOfLife class
* Calls initialize on that instance with the arguments passed to new.
* Returns that instance

Let's define an initialize method!

Footnotes
=========
¹ Class new: http://ruby-doc.org/core-2.0.0/Class.html#method-i-new