RED - Define GameOfLife class
Expected Output
===============
>   1) Error:
>   TestGameOfLife#test_an_empty_world_after_a_single_iteration:
>   NameError: uninitialized constant TestGameOfLife::Iterator
>       test/all.rb:9:in `test_an_empty_world_after_a_single_iteration'

An important part of test driven development is *reading the errors* and
doing *the lest you possibly can* to fix *that particular error*.

The previous error was telling us that there was nothing named GameOfLife.
I defined a class called "GameOfLife" and re-ran the tests. This
caused the message to change in a way I anticipated (a Good Thing™)

The current error says there's nothing named `Iterator`, so what do you
think I'll do next?

Synax Breakdown
===============

`class GameOfLife ... end` - Defines a class named "GameOfLife"