RED - define a run! instance method on GameOfLife
Expected Result of `ruby test/all.rb`
====================================
>    1) Error:
>  TestGameOfLife#test_an_empty_world_after_a_single_iteration:
>  NoMethodError: undefined method `world' for #<GameOfLife:0x007f81e492d868>
>      test/all.rb:20:in `test_an_empty_world_after_a_single_iteration'

Previous Result of `ruby test/all.rb`
=====================================
>     1) Error:
>   TestGameOfLife#test_an_empty_world_after_a_single_iteration:
>   NoMethodError: undefined method `run!' for #<GameOfLife:0x007ffadb936218>
>       test/all.rb:16:in `test_an_empty_world_after_a_single_iteration'

Again, we can see from the previous failure what to do:
 * "test/all.rb:16" tells us where the problem is in  our code (the "act"
    part of Arrange/act/assert)
 * "undefined method `run!' for #<GameOfLife:0xGibberish>" - Tells us that ruby
   expects an instance method named `run!` to exist on the `GameOfLife` class.
 * `#<GameOfLife:0xGibberish>` - This tells us the error occured on an an
   instance of the GameOfLife class. On the left of the `:` is the class, on
   the right is a bunch of letters and numbers known as the "instance id".

With these two bits of information, I define a `run!` instance method and
continue merrily on my way.